// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gapenxfjzhngarsltlwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhcGVueGZqemhuZ2Fyc2x0bHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDc4NjYsImV4cCI6MjA2NDg4Mzg2Nn0.8RbYyjHlaU5okYn-1ml07kRpVlA_85NGI0V8gg0Clj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);